server:
        servlet:
                context-path: /api
        port: 8888

spring:
        datasource:
                url: jdbc:postgresql://IP:5432/icpc_information_system?currentSchema=icpc_information_system
                username: gaussdb
                password: PWD
                driverClassName: org.postgresql.Driver
        redis:
                host: 192.168.xx.xx
                port: 6379
                password: 123456
                jedis:
                        pool:
                                max-active: 8
                                max-wait: -1
                                max-idle: 500
                                min-idle: 0
                lettuce:
                        shutdown-timeout: 0

mybatis:
        mapper-locations: classpath:mapping/*.xml
        type-aliases-package: com.IcpcInformationSystemBackend.model.entity

ENCODE_KEY: <YOUR ENCODE KEY HERE>

logging:
        level:
                com.IcpcInformationSystemBackend: debug
